language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-25
    - ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.3
  - android-25
  - extra-android-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
licenses:
  - 'android-sdk-license-.+'
before_script:
  - chmod +x ./gradlew
script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - ./gradlew createDebugCoverageReport coveralls
after_success:
  - bash <(curl -s https://codecov.io/bash)
